
-- Create guests table
CREATE TABLE guests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  fullName text,
  email text,
  nationality text,
  nationalID text,
  countryFlag text
);

-- Create cabins table (Lodge)
CREATE TABLE cabins (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  name text,
  maxCapacity int,
  regularPrice int,
  discount int,
  description text,
  image text
);

-- Create settings table
CREATE TABLE settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  minBookingLength int,
  maxBookingLength int,
  maxGuestsPerBooking int,
  breakfastPrice int
);

-- Create tours table
CREATE TABLE tours (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  duration_days int,
  price int,
  difficulty text,
  description text,
  image text
);

-- Create destinations table
CREATE TABLE destinations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  region text,
  description text,
  image text,
  highlights text[]
);

-- Create bookings table (Lodge Reservations)
CREATE TABLE bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  num_nights int,
  num_guests int,
  total_price int,
  cabin_price int,
  extras_price int,
  status text,
  has_breakfast boolean,
  is_paid boolean,
  observations text,
  cabin_id bigint REFERENCES cabins(id),
  guest_id bigint REFERENCES guests(id)
);

-- Create tour_bookings table
CREATE TABLE tour_bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  order_date timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  num_guests int NOT NULL DEFAULT 1,
  total_price int NOT NULL,
  status text DEFAULT 'unconfirmed',
  is_paid boolean DEFAULT false,
  tour_id bigint REFERENCES tours(id),
  guest_id bigint REFERENCES guests(id)
);

-- Insert sample settings
INSERT INTO settings (minBookingLength, maxBookingLength, maxGuestsPerBooking, breakfastPrice)
VALUES (3, 90, 10, 15);

-- Insert sample cabins
INSERT INTO cabins (name, maxCapacity, regularPrice, discount, image, description)
VALUES 
('001', 2, 250, 0, 'https://ytreuzebgsogmyuxrzee.supabase.co/storage/v1/object/public/cabin-images/cabin-001.jpg', 'A small luxury cabin in the woods.'),
('002', 2, 350, 25, 'https://ytreuzebgsogmyuxrzee.supabase.co/storage/v1/object/public/cabin-images/cabin-002.jpg', 'Cozy cabin with a view.'),
('003', 4, 300, 0, 'https://ytreuzebgsogmyuxrzee.supabase.co/storage/v1/object/public/cabin-images/cabin-003.jpg', 'Family cabin near the lake.'),
('004', 4, 500, 50, 'https://ytreuzebgsogmyuxrzee.supabase.co/storage/v1/object/public/cabin-images/cabin-004.jpg', 'Luxury cabin for small groups.'),
('005', 6, 800, 100, 'https://ytreuzebgsogmyuxrzee.supabase.co/storage/v1/object/public/cabin-images/cabin-005.jpg', 'Large cabin suitable for events.');

-- Insert sample tours
INSERT INTO tours (name, duration_days, price, difficulty, description, image) VALUES
('The Imperial Road', 12, 2800, 'Easy', 'A majestic trek thru history.', 'https://ytreuzebgsogmyuxrzee.supabase.co/storage/v1/object/public/ethiocabin/download%20(2).webp'),
('Danakil Expedition', 4, 1500, 'Challenging', 'Volcano adventure.', 'https://ytreuzebgsogmyuxrzee.supabase.co/storage/v1/object/public/ethiocabin/ertale.webp');

-- Insert sample destinations
INSERT INTO destinations (name, region, description, image, highlights) VALUES
('Aksum', 'Tigray', 'Ancient giant obelisks and history.', 'https://ytreuzebgsogmyuxrzee.supabase.co/storage/v1/object/public/ethiocabin/Aksum.webp', ARRAY['Ancient Stele']),
('Gondar', 'Amhara', 'The majestic Fasil Ghebbi royal enclosure.', 'https://ytreuzebgsogmyuxrzee.supabase.co/storage/v1/object/public/ethiocabin/Gondar.webp', ARRAY['Imperial Castles']),
('Addis Ababa', 'Central', 'Vibrant capital of Africa.', 'https://ytreuzebgsogmyuxrzee.supabase.co/storage/v1/object/public/ethiocabin/AddisAbaba.webp', ARRAY['National Museum']),
('Simien Park', 'Amhara', 'Roof of Africa.', 'https://ytreuzebgsogmyuxrzee.supabase.co/storage/v1/object/public/ethiocabin/SimienPark.webp', ARRAY['Highland Trekking']);

-- Enable RLS
ALTER TABLE tour_bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public for all" ON tour_bookings FOR ALL USING (true);
CREATE POLICY "Public for all" ON bookings FOR ALL USING (true);
